[project]
name = "beholder"
version = "0.1.0"
description = "Async API clients for London Beauty Heatmap bulk sampling and testing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "h3>=4.3.1",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
