name = "beholder"
main = "worker.js"
compatibility_date = "2025-08-03"

[vars]
# Public variables (sensitive values set via wrangler secret put)
# GEMINI_API_KEY = "set via wrangler secret put"
# GOOGLE_MAPS_API_KEY = "set via wrangler secret put"

# CORS settings
CORS_ORIGIN = "*"

# Rate limiting
MAX_REQUESTS_PER_MINUTE = "60"

[[d1_databases]]
binding = "DB"
database_name = "beholder"
database_id = "fed59963-34cd-45fe-8c8a-b3b72141ac77"